# -*- coding: utf-8 -*-
"""DataScience_Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwH4DXJzQEeDL-gIaCQLXG94l9c5-yPM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

readings = pd.read_csv('Mall_Customers.csv')

readings.head()

readings.info()

readings.describe()

readings.columns

"""Que 1: Finding a range of customers according to age group in Mall_Customers."""

plt.figure(figsize=(10,5))
sns.histplot(x='Age',data=readings)

plt.figure(figsize=(14,7))
sns.countplot(x='Age',data=readings,hue="Genre")

"""***1st que solution***- From Graph, female with age group-23,31,35,49 and male with age group-19,32,48,59 usually go to mall.

Que 2: Relation between age and Spending Score below
"""

plt.figure(figsize=(16,8))
sns.barplot(x='Age',y="Spending Score (1-100)",data=readings,ci=None)

"""***2nd que solution***- From above graph approximately we can see that people's age ranging between 18-39 spend higher as compare to age group of people between 40-70

Que 2: Relation between age and annual income below
"""

plt.figure(figsize=(16,8))
sns.barplot(x="Age",y="Annual Income (k$)", data=readings,ci=None)

"""***2nd que solution***- From above graph approximately we can see that people's age ranging between 28-47 have higher annual income as compare to other age group of people.

Que 3: Cluster of Annual Income (k$) vs Spending Score and observation reading accordingly
"""

plt.figure(figsize=(16,8))
plt.scatter(x="Annual Income (k$)",y="Spending Score (1-100)",c="Spending Score (1-100)",data=readings)
plt.xlabel=('Annual Income')
plt.ylabel=('Spending Score')
plt.legend()
plt.show()

"""
***3rd que solution***- By seeing above plot we can say no of clusters is 5 i.e approximately from 15-37, 38-70, 71-90, 91-110, 111-140 for x values. So to check using official method below i use Elbow Method to cross check.
**Readings:**
1)People having annual income between 20-40 have spending value between 0-40 and 60-90 in k dollar. 
2)People having annual income between 40-70 have spending value between 40-60 in k dollar"""

#Model Traning for elbow point
from sklearn.cluster import KMeans
kmeansforyvalue=[] 
for k in range(1,30): 
  fit_kmeans = KMeans(n_clusters=k)
  fit_kmeans.fit(readings.iloc[:,3:4]) 
  kmeansforyvalue.append(fit_kmeans.inertia_)

#ploting elbow point
plt.plot(range(1,30),kmeansforyvalue,marker='x')
plt.show()

"""From plot it can be seen that after 5 cross marks the graph is almost linear. So Verified i.e no of clusters are 5."""